server:
  port: 8081

spring:
  application:
    name: woolly-wonders
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/woolly-wonders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method